title: Microsoft365.com/setup - Microsoft365/setup
Description: Visit the Microsoft365.com/setup webpage to download the setup. Sign in with your Microsoft account using your email and password. 
theme: jekyll-theme-slate
